
- name: Collect the host and build the resulting host list
  ansible.builtin.set_fact:
    _hosts: "{{ _hosts|default([]) + [ hostvars[item]['ansible_hostname'] ] }}"
  loop: "{{ groups['edpm'] }}"

- name: Create dashboard spec
  ansible.builtin.template:
    src: templates/ceph_dashboard.yml.j2
    dest: "{{ cifmw_ceph_dashboard_spec_path }}"
    mode: '0644'
    force: true

- name: Config ssl cert(s) and key(s) for the exposed components
  become: true
  block:
    - name: Get ceph_cli
      include_tasks: ceph_cli.yaml
      vars:
        mount_certs: true

    - name: import grafana certificate file
      command: "{{ tripleo_cephadm_ceph_cli }} config-key set mgr/cephadm/grafana_crt -i {{ tripleo_cephadm_grafana_crt }}"
      changed_when: false

    - name: import grafana certificate key
      command: "{{ tripleo_cephadm_ceph_cli }} config-key set mgr/cephadm/grafana_key -i {{ tripleo_cephadm_grafana_key }}"
      changed_when: false
  when: cifmw_cephadm_dashboard_protocol == "https" and
        cifmw_cephadm_grafana_crt | length > 0 and cifmw_cephadm_grafana_key | length > 0

- name: Get ceph_cli
  ansible.builtin.include_tasks: ceph_cli.yml
  vars:
    mount_spec: true
    cifmw_cephadm_spec: "{{ cifmw_ceph_dashboard_spec_path }}"

- name: Apply spec
  ansible.builtin.command: "{{ cifmw_cephadm_ceph_cli }} orch apply --in-file {{ cifmw_cephadm_container_spec }}"
  become: true

